parameters:
    # PHP CS
    tasks.phpcs.standard: PSR12
    tasks.phpcs.ignore_patterns:
        - "/build/"
        - "/benchmarks/"
        - "/node_modules/"
        - "/spec/"
        - "/tests/"
        - "/var/"
        - "/vendor/"
    tasks.phpcs.triggered_by:
        - php

    # Twigcs
    tasks.twigcs.path: src
    tasks.twigcs.triggered_by: ['twig']
    tasks.twigcs.ruleset: 'FriendsOfTwig\Twigcs\Ruleset\Official'
    tasks.twigcs.severity: 'error'

    # Security Checker
    tasks.securitychecker.format: ~
    tasks.securitychecker.end_point: ~
    tasks.securitychecker.timeout: ~
    tasks.securitychecker.lockfile: ./composer.lock

grumphp:
    process_timeout: null
    parallel:
        enabled: false
        max_workers: 32
    fixer:
        enabled: true
        fix_by_default: false

    extensions:
        - Robolo\ConventionsPhp\GrumphpTasksExtension

    # Testsuites
    testsuites:
        cs:
            tasks:
                - composer
                - composer_normalize
                - yamllint
                - phplint
                - twigcs
                - phpcs

        static-analysis:
            tasks:
                - phpstan

        security:
            tasks:
                - securitychecker

    # Tasks.
    tasks:
        # Security Checker
        securitychecker:
            lockfile: '%tasks.securitychecker.lockfile%'
            format: '%tasks.securitychecker.format%'
            end_point: '%tasks.securitychecker.end_point%'
            timeout: '%tasks.securitychecker.timeout%'
            run_always: false

        # Composer checks
        composer: ~

        # Composer Normalize
        composer_normalize: ~

        # YAML Lint
        yamllint:
            whitelist_patterns: []
            ignore_patterns: []
            object_support: true
            exception_on_invalid_type: true
            parse_constant: true
            parse_custom_tags: true

        # JSON Lint
        jsonlint:
            ignore_patterns: []
            detect_key_conflicts: true

        # PHP Lint
        phplint: ~

        # Twig CS
        twigcs:
            path: '%tasks.twigcs.path%'
            ruleset: '%tasks.twigcs.ruleset%'
            severity: '%tasks.twigcs.severity%'
            triggered_by: '%tasks.twigcs.triggered_by%'

        # PHP CS
        phpcs:
            standard: '%tasks.phpcs.standard%'
            ignore_patterns: '%tasks.phpcs.ignore_patterns%'
            triggered_by: '%tasks.phpcs.triggered_by%'

        # GIT pre-commit message checker
        git_commit_message:
            allow_empty_message: false
            enforce_capitalized_subject: true
            enforce_no_subject_punctuations: false
            enforce_no_subject_trailing_period: false
            enforce_single_lined_subject: true
            type_scope_conventions: []
            max_body_width: 72
            max_subject_width: 80
            matchers:
                Must contain JIRA issue number: '/^GDSREF-\d+: [A-Z].+\./'
            case_insensitive: true
            multiline: true
            additional_modifiers: ''
        
        # GIT pre-branching message checker
        git_branch_name:
            whitelist:
                - '/^(bugfix|hotfix|feature)\/GDSREF-\d+[A-Z|-].+/'
            blacklist:
                - 'develop'
                - 'master'
            additional_modifiers: ''
            allow_detached_head: true
